# application.yml
spring:
  application:
    name: your-app-name
    
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

# Custom JWT configuration
app:
  jwt:
    secret: ${JWT_SECRET:your-super-secret-jwt-key-that-should-be-at-least-256-bits-long-and-stored-securely}
    expiration: 86400000 # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    com.yourapp: DEBUG
    org.springframework.security: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized